### ISSUE TITLE
Upgrade to HA 2023.5.2 causes Heatmiser integration issue

### ISSUE THREAD

**Issue by david-b13** [MindrustUK/Heatmiser-for-home-assistant#131]
My Heatmiser integration has failed to load (tried several times) after upgrading to 2023.5.2.  Anyone else come across this ?  Any fix ?

**Error log shows:**  
        Logger: homeassistant.config_entries
        Source: config_entries.py:367 
        First occurred: 09:43:09 (1 occurrences) 
        Last logged: 09:43:09
        
        Error importing platform config_flow from integration heatmiserneo to set up heatmiserneo configuration entry: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)

**Comment by mpredfearn** [comment]
This was fixed last week by https://github.com/MindrustUK/Heatmiser-for-home-assistant/commit/02c1ae1274835106b00a52c54a81e371a9cc79e0. Update the repository through HACS.
