### ISSUE TITLE
Integration stopped working in 2023.5.0

### ISSUE THREAD

**Issue by Plawasan** [MindrustUK/Heatmiser-for-home-assistant#129]
Integration will not load after upgrading to 2023.5.0, running the latest release (bd425c3)

```
Logger: homeassistant.config_entries
Source: config_entries.py:367
First occurred: 10:41:25 PM (1 occurrences)
Last logged: 10:41:25 PM

Error importing platform config_flow from integration heatmiserneo to set up heatmiserneo configuration entry: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
```

I've also tried installing the integration from scratch in my test instance running 2023.5.0b8 (a bit late...), getting the following error:
```
Error
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

Thanks

**Comment by jamespreedy** [comment]
Same here sadly. Same error.
Please let me know if any additional information would help at all - thanks!

**Comment by iandarbeynhiu** [comment]
I've the same issue. Happy to pull logs etc. Just upgraded to 2023.5.

**Comment by iandarbey** [comment]
I've the same issue. Happy to pull logs etc. Just upgraded to 2023.5.

**Comment by MindrustUK** [comment]
Just patched the offending issue. Please grab the latest version of the integration (specifically config_flow.py was changed)  and if someone can confirm that the issue is resolved I'll close the ticket.

**Comment by Plawasan** [comment]
> Just patched the offending issue. Please grab the latest version of the integration (specifically config_flow.py was changed) and if someone can confirm that the issue is resolved I'll close the ticket.

Initial check on b8 looks good, will upgrade my prod instance and close the issues if it solves it.

Thanks for the quick response!

**Comment by jamespreedy** [comment]
The update works here - thanks so much for the quick turnaround! 🍺

**Comment by Plawasan** [comment]
Working now after upgrading to 02c1ae1... much appreciated!

(I just wonder what the turnaround would be if this was an official integration by Heatmiser... )
